// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hzgscfjfhezutlyvkbyw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh6Z3NjZmpmaGV6dXRseXZrYnl3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0NTMxMTgsImV4cCI6MjA2NTAyOTExOH0.seXKnIy2ZVFonR1QPH0njB4H_Z7zng_5OD4C43iB4ds";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);